# terraform의 infra/ansible_vars.tf에 의해 생성되는 파일
[proxy]
instance1 ansible_host=192.168.247.221 ansible_user=ubuntu ansible_ssh_private_key_file=/root/mykey1.pem

[backend]
instance2 ansible_host=172.16.222.156 ansible_user=ubuntu ansible_ssh_private_key_file=/root/mykey2.pem

[backend:vars]
ansible_ssh_common_args="-o ProxyCommand='ssh -i /root/mykey1.pem -W %h:%p -q ubuntu@192.168.247.221 -o StrictHostKeyChecking=no' -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"